import { TrainingMode } from "@/types/training";
import {
  BetSizeTrainer,
  BluffTrainer,
  BoardTextureTrainer,
  ComboCountingTrainer,
  DecisionTreeTrainer,
  EquityTrainer,
  HandAnalyzer,
  HandReadingTrainer,
  HudTrainer,
  MentalGameTrainer,
  OutsTrainer,
  PlayerTypesTrainer,
  PositionTrainer,
  PotOddsTrainer,
  PreflopTrainer,
  RangeBuilderTrainer,
  RangeTrainer,
  ReplaySimulator,
  RiverTrainer,
  ScenarioBuilder,
  SemiBluffTrainer,
  SessionReview,
  SprTrainer,
  StackDepthTrainer,
  ValueBettingTrainer,
  VillainProfilingTrainer,
} from "@/modes";

/** Maps every training mode to the React component that renders its drill. */
export const MODE_COMPONENT: Record<TrainingMode, React.ComponentType> = {
  [TrainingMode.Preflop]: PreflopTrainer,
  [TrainingMode.Position]: PositionTrainer,
  [TrainingMode.Outs]: OutsTrainer,
  [TrainingMode.PotOdds]: PotOddsTrainer,
  [TrainingMode.Equity]: EquityTrainer,
  [TrainingMode.BoardTexture]: BoardTextureTrainer,
  [TrainingMode.BetSize]: BetSizeTrainer,
  [TrainingMode.Range]: RangeTrainer,
  [TrainingMode.RangeBuilder]: RangeBuilderTrainer,
  [TrainingMode.HandReading]: HandReadingTrainer,
  [TrainingMode.StackDepth]: StackDepthTrainer,
  [TrainingMode.Spr]: SprTrainer,
  [TrainingMode.PlayerTypes]: PlayerTypesTrainer,
  [TrainingMode.Bluff]: BluffTrainer,
  [TrainingMode.SemiBluff]: SemiBluffTrainer,
  [TrainingMode.ValueBetting]: ValueBettingTrainer,
  [TrainingMode.River]: RiverTrainer,
  [TrainingMode.ComboCounting]: ComboCountingTrainer,
  [TrainingMode.DecisionTree]: DecisionTreeTrainer,
  [TrainingMode.VillainProfiling]: VillainProfilingTrainer,
  [TrainingMode.Hud]: HudTrainer,
  [TrainingMode.MentalGame]: MentalGameTrainer,
  [TrainingMode.SessionReview]: SessionReview,
  [TrainingMode.HandAnalyzer]: HandAnalyzer,
  [TrainingMode.Replay]: ReplaySimulator,
  [TrainingMode.ScenarioBuilder]: ScenarioBuilder,
};
